### ISSUE TITLE
App crash on MainActivity

### ISSUE THREAD

**Issue by LetsNurtureGit** [alejandrorosas/android-uvc-rtmp-stream#16]
It's crashing on launch and below report is found:

 Process: dev.alejandrorosas.apptemplate, PID: 14192
    java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method
        at dev.alejandrorosas.apptemplate.MainActivity.onCreate(MainActivity.kt:35)

Can you please fix? Are you able to access UVC camera and stream is working in your demo?

**Comment by alejandrorosas** [comment]
Hey @LetsNurtureGit I just fixed it by reverting the latest commit that was updating Kotlin to 1.5 https://github.com/alejandrorosas/android-uvc-rtmp-stream/pull/17
