### ISSUE TITLE
Android target

### ISSUE THREAD

**Issue by mylaimani** [alejandrorosas/android-uvc-rtmp-stream#18]
Is there any way to set targetSdkVersion to 29 or 30

When I try to change the target to 30, application gets crashed

**Comment by alejandrorosas** [comment]
There's an issue with trying to get permission when you set the target SDK version of your app to 30. It was reported here https://issuetracker.google.com/issues/145082934 and you can find some investigations around that in here: https://github.com/saki4510t/UVCPermissionTest
