### ISSUE TITLE
no audio! just screen

### ISSUE THREAD

**Issue by myousefi1368** [alejandrorosas/android-uvc-rtmp-stream#76]
thanx for your good app
but i can't get audio of usb camera via usb source.
so the streaming video doesn't have audio.

**Comment by myousefi1368** [comment]
I test app in androide 11 and hopefully it works well (video and audio). 
but in android 10 it doesn't have audio.

best app i see in live broadcasting....
thanx 
thanx
thanx

**Comment by alejandrorosas** [comment]
I'm planning on just supporting latest versions so android 11, given my Pixel 4 was restarting all the time when I was using Android 10, so better to use it with Android 11 if possible
