### ISSUE TITLE
Unrecognized Android Studio (or Android Support plugin for IntelliJ IDEA) version '202.7660.26.42.7486908', please retry with version 2020.3.1 or newer.

### ISSUE THREAD

**Issue by Allan-Nava** [alejandrorosas/android-uvc-rtmp-stream#80]

**Comment by alejandrorosas** [comment]
It looks you might be using IntelliJ IDEA instead, you should be using Android Studio to build this project, you can download it from the official webpage https://developer.android.com/studio

**Comment by Allan-Nava** [comment]
I used android studio but I have this problem:

![Screenshot 2021-12-09 at 11 18 14](https://user-images.githubusercontent.com/22498435/145378003-46a8693c-1008-4ffb-bf53-e863803f6a7b.png)

**Comment by Allan-Nava** [comment]
![Screenshot 2021-12-09 at 11 20 57](https://user-images.githubusercontent.com/22498435/145378392-bf6f3183-ad37-4627-8bc7-842c681b40e5.png)

**Comment by alejandrorosas** [comment]
It looks you are using the previous version to Arctic fox, you can download the latest one from here: https://developer.android.com/studio

**Comment by Allan-Nava** [comment]
```
Execution failed for task ':libraries:libuvccamera:ndkBuild'.
> A problem occurred starting process 'command 'null/ndk-build''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```



I got this problem 
![Screenshot 2021-12-09 at 11 54 37](https://user-images.githubusercontent.com/22498435/145383612-6300b956-1539-4eba-ac92-d60361195891.png)

**Comment by Allan-Nava** [comment]
I have problem with ndk

**Comment by alejandrorosas** [comment]
This is probably because you are missing to define the `ndk.dir` property in `local.properties`. I have a pending refactor to not require this property

**Comment by Allan-Nava** [comment]
Have you published the fix?
