### ISSUE TITLE
Black screen and only audio is sent apparently

### ISSUE THREAD

**Issue by publioelon** [alejandrorosas/android-uvc-rtmp-stream#87]
I downloaded this library to see if I can use my USB camera with it and there is a black screen that won't go away.  Additionally, I can notice there is a huge set of logs printing the audio packets:

```
D/RtmpConnection: wrote packet: RTMP Audio, size: 260
D/RtmpConnection: wrote packet: RTMP Audio, size: 247
D/RtmpConnection: wrote packet: RTMP Audio, size: 253
D/RtmpConnection: wrote packet: RTMP Audio, size: 254
D/RtmpConnection: wrote packet: RTMP Audio, size: 242
D/RtmpConnection: wrote packet: RTMP Audio, size: 257
D/RtmpConnection: wrote packet: RTMP Audio, size: 257
...
```

I tried viewing the stream anyway using VLC, and I notice that it detects the stream and receives it, but no video.
I also tried viewing it on a Python server receiving video only and it doesn't detect any frames to display.

Would you kindly guide me on how to get rid of the black screen and run your library? really need it man.

**Comment by alejandrorosas** [comment]
Hey, does your capture dongle works with 1080? if not you probably have to tweak the value

**Comment by publioelon** [comment]
Actually, now that you mentioned: it is configured by default to MJPEG format, I had to change to YUV
