### ISSUE TITLE
error: Cannot determine word size

### ISSUE THREAD

**Issue by Ivan421399** [alejandrorosas/android-uvc-rtmp-stream#88]
I'm trying to build this app and keep getting this error:
```
.../android-uvc-rtmp-stream/libraries/libuvccamera/jni/libjpeg-turbo-2.0.6/./jchuff.c:391:2: error: Cannot determine word size
#error Cannot determine word size
```
I'm not familiar with libjpeg-turbo, can anyone help me?

Edit: I'm on Ubuntu, is Windows required to build libjpeg-turbo?

**Comment by alejandrorosas** [comment]
Hey, I think it should work on linux, the one I tested and it does not build is in Windows, but I have it running on MacOS so unix, and github actions is using ubuntu, so it should work in linux

**Comment by Ivan421399** [comment]
Maybe it's because I use the older version of Ubuntu. I will post the result in the future. TY

**Comment by Ivan421399** [comment]
I think I know the reason. There is no x86_64 architecture variant in Android.mk for libjpeg-turbo-2.0.6.
I'm using i5-7500 so it is x86_64 architecture. The 1.5.0 version of libjpeg-turbo works fine for me.

Who should I contact with regarding this lib? Because I'm not sure who made your android one.

**Comment by Ivan421399** [comment]
I made your app to run. I simply ran app on a phone instead of building the project with "Make Project" (hammer button).
It looks like the problem is in my IDE.
Sorry for bothering you.

P.S. It still would be very kind if anybody could explain to me how to make "Make Project" to not ignore abi filters.

**Comment by pabiagioli** [comment]
I found the same issue, this is related to the abiFilters. Apparently `x86` and probably `x86_64` is not supported. You need to change the gradle file like this:
https://github.com/alejandrorosas/android-uvc-rtmp-stream/blob/master/libraries/libuvccamera/build.gradle

```groovy
android {
    ndkVersion "22.1.7171670"
    compileSdkVersion 30
    externalNativeBuild {
        ndkBuild {
            path "jni/Android.mk"
        }
    }

    defaultConfig {
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }
    }

    sourceSets.main {
        jni.srcDirs "jni"
    }
}
```

**Comment by alejandrorosas** [comment]
Thanks @pabiagioli just updated the project with your suggestion https://github.com/alejandrorosas/android-uvc-rtmp-stream/pull/99
