### ISSUE TITLE
Showing Blank screen

### ISSUE THREAD

**Issue by LetsNurtureGit** [alejandrorosas/android-uvc-rtmp-stream#91]
I am trying to run this project and I have properly attached the webcam and also enable USB device permission, app permission. It's showing always a blank screen somehow camera is not working with this app. And I have tested webcam with other cam app and it's working fine.

Let me know if I am missing anything! Please guide me

Thanks in advance!

**Comment by Ivan421399** [comment]
@LetsNurtureGit
Are you using android 11 or 12?
If so please can you tell which processor your phone has?

**Comment by LetsNurtureGit** [comment]
I am using android 8,10 and 11.

**Comment by jeffman2020** [comment]
i have same problem with LetsNurtureGit.I use android 10,9. My uvc cam is 640x480 15fps MJpeg.it is blank,black screen.Could u help us?

**Comment by alejandrorosas** [comment]
where do you see the blank screen? Is it on the live stream or on the live preview on the device?

**Comment by jeffman2020** [comment]
preview

在 2022-11-07 03:06:03，"Alejandro Rosas" ***@***.***> 写道：


where do you see the blank screen? Is it on the live stream or on the live preview on the device?

**Comment by alejandrorosas** [comment]
I think I might have found your issue, trying to use a cam of 720 it was showing a black screen, so now I've updated the app to use the best available resolution, you can check this PR https://github.com/alejandrorosas/android-uvc-rtmp-stream/pull/148

**Comment by jeffman2020** [comment]
thanks ,i will try










At 2022-11-28 00:48:13, "Alejandro Rosas" ***@***.***> wrote:

I think I might have found your issue, trying to use a cam of 720 it was showing a black screen, so now I've updated the app to use the best available resolution, you can check this PR #148
